### Recibiendo correo xD
POST http://localhost:2001/api/v1/contact
Content-Type: application/json

{
    "name": "Esperando",
    "email": "olv@gmail.com",
    "message": "Lorem"
}

### Eliminando correo xD
DELETE http://localhost:2001/api/v1/contact/6036f4e949f1ff0ccc486351

### Obteniendo correos xD
GET http://localhost:2001/api/v1/contact

### Obteniendo correo xD
GET http://localhost:2001/api/v1/contact/6036f4e949f1ff0ccc486351
