### Recibiendo correo xD
POST http://localhost:2001/api/v1/contact
Content-Type: application/json

{
    "name": "Esperando",
    "email": "olv@gmail.com",
    "message": "Lorem"
}

### Eliminando correo xD
DELETE http://localhost:2001/api/v1/contact/idprueba

### Obteniendo correos xD
GET http://localhost:2001/api/v1/contact

### Obteniendo correos xD
GET http://localhost:2001/api/v1/contact/idprueba2
