### Recibiendo Imagen
POST http://localhost:2001/api/v1/image
x-access-token: token
Content-Type: multipart/form-data

### Eliminando Imagen
DELETE http://localhost:2001/api/v1/image/603ed41ecccec7069c81460e
x-access-token: token
