### Creando proyecto
POST http://localhost:2001/api/v1/proyect
Content-Type: application/json

{
    "imgUrl": "img2.jpg",
    "name": "Nuevo Proyecto Prueba",
    "description": "Esta es una Descripcion 2",
    "github": "LuisFOsG/prueba2",
    "url": "url del proyecto xd"
}

### Actualizando proyecto
PUT http://localhost:2001/api/v1/proyect/603043209d504a3b1c584255
Content-Type: application/json

{
    "imgUrl": "img.jpg",
    "name": "Nuevo Proyecto",
    "description": "Hola Mundo xd",
    "github": "LuisFOsG/prueba",
    "url": "URL"
}

### Obteniendo proyectos
GET http://localhost:2001/api/v1/proyect

### Obteniendo un solo Proyecto
GET http://localhost:2001/api/v1/proyect/60301aaeafd02d00d016ddab

### Eliminando un Proyecto
DELETE http://localhost:2001/api/v1/proyect/60301af5afd02d00d016ddad

### Obteniendo N proyectos
GET http://localhost:2001/api/v1/proyect/get/0
