### Creando proyecto
POST http://localhost:2001/api/proyect
Content-Type: application/json

{
    "imgUrl": "img2.jpg",
    "name": "Nuevo Proyecto Prueba",
    "description": "Esta es una Descripcion 2",
    "github": "LuisFOsG/prueba2",
    "url": "url del proyecto xd"
}

### Actualizando proyecto
PUT http://localhost:2001/api/proyect/5fffa8f0ea19e53480d3a1a4
Content-Type: application/json

{
    "imgUrl": "img1.jpg",
    "name": "Nuevo Proyecto Prueba",
    "description": "Esta es una Descripcion",
    "github": "LuisFOsG/prueba2",
    "url": "url del proyecto xd"
}

### Obteniendo proyectos
GET http://localhost:2001/api/proyect

### Obteniendo un solo Proyecto
GET http://localhost:2001/api/proyect/5fffb17978aa5a3f983537eb

### Eliminando un Proyecto
DELETE http://localhost:2001/api/proyect/5fffb17978aa5a3f983537eb
