### Creando proyecto
POST http://localhost:2001/api/v1/proyect
x-access-token: token
Content-Type: application/json

{
    "imgUrl": "img2.jpg",
    "nameEs": "Nuevo Proyecto Prueba",
    "nameEn": "New Proyect",
    "descriptionEs": "Esta es una Descripcion 2",
    "descriptionEn": "It is a description",
    "github": "LuisFOsG/prueba2",
    "url": "url del proyecto xd"
}

### Actualizando proyecto
PUT http://localhost:2001/api/v1/proyect/605285566d196f4b5cf61721
x-access-token: token
Content-Type: application/json

{
    "imgUrl": "img.jpg",
    "nameEs": "Nuevo Proyecto Prueba Editado",
    "nameEn": "New Proyect Edit",
    "descriptionEs": "Esta es una Descripcion",
    "descriptionEn": "It is a description 2",
    "github": "LuisFOsG/prueba",
    "url": "url del proyecto xd"
}

### Eliminando un Proyecto
DELETE http://localhost:2001/api/v1/proyect/605285566d196f4b5cf61721
x-access-token: token

### Obteniendo proyectos
GET http://localhost:2001/api/v1/proyect

### Obteniendo un solo Proyecto
GET http://localhost:2001/api/v1/proyect/605282ba925c201a901f8742

### Obteniendo N proyectos
GET http://localhost:2001/api/v1/proyect/get/0
