### Ingresando a la Plataforma
POST http://localhost:2001/api/v1/signin
Content-Type: application/json

{
    "name": "LuisFOsG",
    "password": "Uff Men"
}

### Registrandose a la Plataforma
POST http://localhost:2001/api/v1/user
Content-Type: application/json

{
    "imgUrl": "String",
    "name": "LuisFOsG",
    "description": "Estudiando 2.0",
    "password": "Contraseña xD",
    "github": "LuisFOsG",
    "roles": [ "admin" ]
}

### Editando Usuario xD
PUT http://localhost:2001/api/v1/user/6031bc39a5fa1045e0ccecfd
Content-Type: application/json

{
    "imgUrl": "img xd",
    "name": "",
    "description": "Cambio",
    "password": "cambio",
    "github": "LuisFOsG",
    "roles": [ "admin" ]
}

### Eliminando Usuario xD
DELETE http://localhost:2001/api/v1/user/6031bc39a5fa1045e0ccecfd
