### Ingresando a la Plataforma
POST http://localhost:2001/signin
Content-Type: application/json

{
    "name": "LuisFOsG",
    "password": "**************"
}

### Registrandose a la Plataforma
POST http://localhost:2001/signup
Content-Type: application/json

{
    "imgUrl": "String",
    "name": "LuisFOsG",
    "description": "Estudiando :X",
    "password": "Uff Men",
    "github": "LuisFOsG"
}