### Ingresando a la Plataforma
POST http://localhost:2001/api/v1/signin
Content-Type: application/json

{
    "name": "LuisFOsG",
    "password": "Uff Men"
}

### Registrandose a la Plataforma
POST http://localhost:2001/api/v1/user
Content-Type: application/json

{
    "imgUrl": "String",
    "name": "LuisF",
    "description": "Estudiando 2.0",
    "password": "Contraseña xD",
    "github": "LuisFOsG"
}

### Editando Usuario xD
PUT http://localhost:2001/api/v1/user/602ad0ba9d4c793d207e992f
Content-Type: application/json

{
    "imgUrl": "img xd",
    "name": "",
    "description": "Cambio",
    "password": "cambio",
    "github": "LuisFOsG",
    "roles": []
}

### Eliminando Usuario xD
DELETE http://localhost:2001/api/v1/user/602ad0ba9d4c793d207e992f
